### PR TITLE
la base final avec le AUTO_INREMENT

### PR DESCRIPTION
**Pull request by AhmadSAFAR**

### CODE REVIEW

**Review by RomainClair — CHANGES_REQUESTED** [review]
Readme needs an update.

It probably should be adapted to deal with people having no previous databases or people having a provious database.
Or better : the sql file should deal with it automatically

**Review by RomainClair — APPROVED** [review]
Quiclky reviewed

**Review by AhmadSAFAR — COMMENTED** [review]
j'ai modifé

**Review by AhmadSAFAR — COMMENTED** [review]
modifier le password

**Review by AhmadSAFAR — COMMENTED** [review]
pass

**Pull request merged**
